apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # Rewrite /api/* to /*
    kubernetes.io/ingress.class: "nginx"  # Ensure NGINX Ingress controller
spec:
  ingressClassName: nginx
  rules:
  - host: ecommerce.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
