apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: ecommerce
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=  # base64 for 'admin'
  MONGO_PASSWORD: YWRtaW4xMjM= # base64 for 'admin123'